run-dist :
		./build/install/app/bin/app
run :
		gradle run
clean :
		gradle clean
setup:
		./gradlew wrapper --gradle-version 8.5
install:
		gradle clean install
build :
		gradle clean
		gradle installDist
lint :
		gradle checkstyleMain
